// Exercise database with alternatives
export const exerciseDB = {
  // CHEST
  chest_press_incline: { name: 'Incline Dumbbell Press', muscles: 'Upper chest, front delts', cues: ['30° incline', 'Control negative', 'Full stretch'] },
  chest_press_flat_bb: { name: 'Flat Bench Press', muscles: 'Mid chest, triceps', cues: ['Slight arch', 'Touch mid-chest', 'Drive through floor'] },
  chest_press_flat_db: { name: 'Flat Dumbbell Press', muscles: 'Mid chest, triceps', cues: ['Neutral or pronated grip', 'Full ROM', 'Squeeze at top'] },
  chest_press_machine: { name: 'Machine Chest Press', muscles: 'Chest, triceps', cues: ['Adjust seat height', 'Control the weight', 'Full extension'] },
  chest_fly_cable: { name: 'Cable Fly', muscles: 'Chest', cues: ['Slight elbow bend', 'Squeeze center', 'Slow negative'] },
  chest_fly_machine: { name: 'Pec Deck', muscles: 'Chest', cues: ['Elbows at 90°', 'Squeeze hard', 'Control return'] },
  chest_dip: { name: 'Chest Dip', muscles: 'Lower chest, triceps', cues: ['Lean forward', 'Elbows out', 'Deep stretch'] },
  // SHOULDERS
  shoulder_press_db: { name: 'Seated Dumbbell Press', muscles: 'Front & side delts', cues: ['Neutral spine', 'Full lockout', 'Control descent'] },
  shoulder_press_machine: { name: 'Machine Shoulder Press', muscles: 'Shoulders', cues: ['Back against pad', 'Full ROM', 'Don\'t lock'] },
  shoulder_press_bb: { name: 'Overhead Barbell Press', muscles: 'Shoulders, triceps', cues: ['Tight core', 'Bar path straight', 'Full lockout'] },
  lateral_raise_db: { name: 'Dumbbell Lateral Raise', muscles: 'Side delts', cues: ['Lead with elbows', 'Stop at shoulder', 'No swinging'] },
  lateral_raise_cable: { name: 'Cable Lateral Raise', muscles: 'Side delts', cues: ['Constant tension', 'Slight lean', 'Control'] },
  lateral_raise_machine: { name: 'Machine Lateral Raise', muscles: 'Side delts', cues: ['Adjust pad height', 'Squeeze at top', 'Slow negative'] },
  // TRICEPS
  tricep_pushdown_rope: { name: 'Rope Pushdown', muscles: 'Triceps', cues: ['Elbows pinned', 'Spread rope', 'Full extension'] },
  tricep_pushdown_bar: { name: 'Bar Pushdown', muscles: 'Triceps', cues: ['Straight bar', 'Elbows still', 'Squeeze'] },
  tricep_overhead_cable: { name: 'Overhead Cable Extension', muscles: 'Triceps long head', cues: ['Elbows forward', 'Full stretch', 'Control'] },
  tricep_overhead_db: { name: 'Overhead Dumbbell Extension', muscles: 'Triceps long head', cues: ['Both hands on DB', 'Elbows in', 'Full ROM'] },
  tricep_skullcrusher: { name: 'Skull Crushers', muscles: 'Triceps', cues: ['Lower to forehead', 'Elbows still', 'EZ bar or DB'] },
  tricep_dip: { name: 'Tricep Dip', muscles: 'Triceps, chest', cues: ['Upright torso', 'Elbows back', 'Full lockout'] },
  tricep_kickback: { name: 'Tricep Kickback', muscles: 'Triceps', cues: ['Upper arm parallel', 'Full extension', 'Squeeze'] },
  // BACK
  lat_pulldown: { name: 'Lat Pulldown', muscles: 'Lats, biceps', cues: ['Slight lean', 'Pull to chest', 'Full stretch'] },
  lat_pulldown_close: { name: 'Close Grip Pulldown', muscles: 'Lats, mid-back', cues: ['V-bar attachment', 'Squeeze lats', 'Control up'] },
  pullup: { name: 'Pull-Up', muscles: 'Lats, biceps', cues: ['Dead hang start', 'Chin over bar', 'Control descent'] },
  pullup_assisted: { name: 'Assisted Pull-Up', muscles: 'Lats, biceps', cues: ['Machine or band', 'Full ROM', 'Build strength'] },
  row_barbell: { name: 'Barbell Row', muscles: 'Mid-back, lats', cues: ['Hinge at hips', 'Pull to belly', 'Squeeze blades'] },
  row_dumbbell: { name: 'Dumbbell Row', muscles: 'Lats, mid-back', cues: ['Knee on bench', 'Pull to hip', 'Full stretch'] },
  row_cable_seated: { name: 'Seated Cable Row', muscles: 'Mid-back', cues: ['Chest up', 'Pull to stomach', 'Squeeze'] },
  row_chest_supported: { name: 'Chest Supported Row', muscles: 'Mid-back, rear delts', cues: ['Chest on pad', 'No momentum', 'Squeeze'] },
  row_machine: { name: 'Machine Row', muscles: 'Mid-back', cues: ['Adjust chest pad', 'Full ROM', 'Control'] },
  face_pull: { name: 'Face Pull', muscles: 'Rear delts, rotator cuff', cues: ['High pull', 'External rotate', 'Squeeze'] },
  rear_delt_fly_cable: { name: 'Cable Rear Delt Fly', muscles: 'Rear delts', cues: ['Cross cables', 'Lead with elbows', 'Squeeze'] },
  rear_delt_fly_machine: { name: 'Reverse Pec Deck', muscles: 'Rear delts', cues: ['Chest on pad', 'Arms straight', 'Squeeze back'] },
  // BICEPS
  curl_barbell: { name: 'Barbell Curl', muscles: 'Biceps', cues: ['Elbows pinned', 'Full ROM', 'No swinging'] },
  curl_dumbbell: { name: 'Dumbbell Curl', muscles: 'Biceps', cues: ['Supinate at top', 'Control negative', 'Alternate or together'] },
  curl_incline: { name: 'Incline Dumbbell Curl', muscles: 'Biceps (stretched)', cues: ['Arms hang back', 'No swinging', 'Full stretch'] },
  curl_preacher: { name: 'Preacher Curl', muscles: 'Biceps', cues: ['Armpits on pad', 'Full extension', 'Squeeze at top'] },
  curl_cable: { name: 'Cable Curl', muscles: 'Biceps', cues: ['Constant tension', 'Elbows still', 'Squeeze'] },
  curl_hammer: { name: 'Hammer Curl', muscles: 'Brachialis, forearms', cues: ['Neutral grip', 'Elbows pinned', 'Control'] },
  curl_reverse: { name: 'Reverse Curl', muscles: 'Forearm extensors', cues: ['Overhand grip', 'Wrists straight', 'Squeeze'] },
  // QUADS
  squat_hack: { name: 'Hack Squat', muscles: 'Quads, glutes', cues: ['Back on pad', 'Full depth', 'Drive through heels'] },
  squat_barbell: { name: 'Barbell Squat', muscles: 'Quads, glutes', cues: ['Bar on traps', 'Break at hips', 'Knees out'] },
  squat_goblet: { name: 'Goblet Squat', muscles: 'Quads, glutes', cues: ['DB at chest', 'Elbows inside knees', 'Upright'] },
  leg_press: { name: 'Leg Press', muscles: 'Quads, glutes', cues: ['Feet shoulder width', 'Full depth', 'Don\'t lock'] },
  leg_extension: { name: 'Leg Extension', muscles: 'Quads', cues: ['Full extension', 'Squeeze at top', '2s hold'] },
  lunge_walking: { name: 'Walking Lunge', muscles: 'Quads, glutes', cues: ['Long stride', 'Knee over toe', 'Upright torso'] },
  lunge_reverse: { name: 'Reverse Lunge', muscles: 'Quads, glutes', cues: ['Step back', 'Front knee stable', 'Drive up'] },
  split_squat_bulgarian: { name: 'Bulgarian Split Squat', muscles: 'Quads, glutes', cues: ['Rear foot elevated', 'Upright', 'Full depth'] },
  // HAMSTRINGS & GLUTES
  rdl_barbell: { name: 'Romanian Deadlift', muscles: 'Hamstrings, glutes', cues: ['Push hips back', 'Slight knee bend', 'Feel stretch'] },
  rdl_dumbbell: { name: 'Dumbbell RDL', muscles: 'Hamstrings, glutes', cues: ['DBs close to legs', 'Hinge pattern', 'Squeeze glutes'] },
  leg_curl_lying: { name: 'Lying Leg Curl', muscles: 'Hamstrings', cues: ['Hips down', 'Full ROM', 'Squeeze'] },
  leg_curl_seated: { name: 'Seated Leg Curl', muscles: 'Hamstrings', cues: ['Adjust pad', 'Full curl', 'Control'] },
  hip_thrust_barbell: { name: 'Barbell Hip Thrust', muscles: 'Glutes', cues: ['Upper back on bench', 'Drive through heels', 'Squeeze top'] },
  hip_thrust_machine: { name: 'Machine Hip Thrust', muscles: 'Glutes', cues: ['Adjust pad', 'Full extension', 'Pause at top'] },
  // CALVES
  calf_raise_standing: { name: 'Standing Calf Raise', muscles: 'Gastrocnemius', cues: ['Full stretch', 'Pause at top', 'Slow negative'] },
  calf_raise_seated: { name: 'Seated Calf Raise', muscles: 'Soleus', cues: ['Knees at 90°', 'Full ROM', 'Squeeze'] },
  calf_raise_leg_press: { name: 'Leg Press Calf Raise', muscles: 'Calves', cues: ['Balls of feet', 'Full extension', 'Control'] },
  // ABS
  crunch_cable: { name: 'Cable Crunch', muscles: 'Abs', cues: ['Crunch ribs to hips', 'Hold', 'Slow negative'] },
  crunch_machine: { name: 'Ab Machine', muscles: 'Abs', cues: ['Adjust weight', 'Crunch down', 'Control'] },
  leg_raise_hanging: { name: 'Hanging Leg Raise', muscles: 'Lower abs', cues: ['Curl pelvis', 'Control swing', 'Slow down'] },
  plank: { name: 'Plank', muscles: 'Core', cues: ['Straight line', 'Squeeze everything', 'Breathe'] },
};

export const alternatives = {
  chest_press_incline: ['chest_press_flat_db', 'chest_press_machine', 'chest_dip'],
  chest_press_flat_bb: ['chest_press_flat_db', 'chest_press_machine', 'chest_dip'],
  chest_fly_cable: ['chest_fly_machine', 'chest_press_flat_db'],
  shoulder_press_db: ['shoulder_press_machine', 'shoulder_press_bb'],
  lateral_raise_db: ['lateral_raise_cable', 'lateral_raise_machine'],
  tricep_pushdown_rope: ['tricep_pushdown_bar', 'tricep_kickback', 'tricep_dip'],
  tricep_overhead_cable: ['tricep_overhead_db', 'tricep_skullcrusher'],
  lat_pulldown: ['lat_pulldown_close', 'pullup', 'pullup_assisted'],
  row_barbell: ['row_dumbbell', 'row_cable_seated', 'row_chest_supported', 'row_machine'],
  row_chest_supported: ['row_dumbbell', 'row_machine', 'row_cable_seated'],
  face_pull: ['rear_delt_fly_cable', 'rear_delt_fly_machine'],
  curl_incline: ['curl_preacher', 'curl_cable', 'curl_dumbbell'],
  curl_hammer: ['curl_reverse', 'curl_cable'],
  leg_press: ['squat_hack', 'squat_barbell', 'squat_goblet'],
  rdl_barbell: ['rdl_dumbbell', 'leg_curl_lying'],
  leg_extension: ['lunge_walking', 'split_squat_bulgarian'],
  leg_curl_lying: ['leg_curl_seated', 'rdl_dumbbell'],
  split_squat_bulgarian: ['lunge_reverse', 'lunge_walking'],
  calf_raise_standing: ['calf_raise_leg_press', 'calf_raise_seated'],
  crunch_cable: ['crunch_machine', 'leg_raise_hanging', 'plank'],
};

export const workoutTemplates = {
  push: [
    { id: 'chest_press_incline', sets: 3, reps: '8-10' },
    { id: 'chest_press_flat_bb', sets: 3, reps: '6-8' },
    { id: 'chest_fly_cable', sets: 3, reps: '12-15' },
    { id: 'shoulder_press_db', sets: 3, reps: '8-10' },
    { id: 'lateral_raise_db', sets: 3, reps: '12-15' },
    { id: 'tricep_pushdown_rope', sets: 3, reps: '10-12' },
    { id: 'tricep_overhead_cable', sets: 2, reps: '10-12' },
    { id: 'crunch_cable', sets: 2, reps: '15-20' },
  ],
  pull: [
    { id: 'lat_pulldown', sets: 3, reps: '8-10' },
    { id: 'row_barbell', sets: 3, reps: '8-10' },
    { id: 'row_chest_supported', sets: 3, reps: '10-12' },
    { id: 'face_pull', sets: 3, reps: '15-20' },
    { id: 'curl_incline', sets: 3, reps: '10-12' },
    { id: 'curl_hammer', sets: 3, reps: '10-12' },
    { id: 'curl_reverse', sets: 2, reps: '12-15' },
  ],
  legs: [
    { id: 'leg_press', sets: 4, reps: '10-12' },
    { id: 'rdl_barbell', sets: 3, reps: '8-10' },
    { id: 'leg_extension', sets: 3, reps: '12-15' },
    { id: 'leg_curl_lying', sets: 3, reps: '10-12' },
    { id: 'split_squat_bulgarian', sets: 3, reps: '10 each' },
    { id: 'calf_raise_standing', sets: 3, reps: '12-15' },
  ],
  cardio: [
    { id: 'cardio_warmup', sets: 1, reps: '5 min', name: 'Warm-up', muscles: 'Full body' },
    { id: 'cardio_main', sets: 1, reps: '20-30 min', name: 'Steady State Cardio', muscles: 'Cardiovascular' },
    { id: 'cardio_cooldown', sets: 1, reps: '5 min', name: 'Cool-down', muscles: 'Recovery' },
  ],
};

export const workoutTypes = {
  push: { name: 'Push', subtitle: 'Chest · Shoulders · Triceps', color: '#3b82f6' },
  pull: { name: 'Pull', subtitle: 'Back · Biceps · Forearms', color: '#8b5cf6' },
  legs: { name: 'Legs', subtitle: 'Quads · Hamstrings · Glutes', color: '#f97316' },
  cardio: { name: 'Cardio', subtitle: 'Heart health · Recovery', color: '#10b981' },
};
